project:
  type: book

book:
  title: "Algorithms & Data Structures Notes - SoSe 24"
  author: "Igor Dimitrov"
  date: "4/22/2024"
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
        - 02-intro/02-analysis.qmd
    - part: "Data Structures"
      chapters:
        - 03/01-lists.qmd
<<<<<<< HEAD
        - 03/02-arrays.qmd

  # downloads: pdf
=======
  downloads: pdf
>>>>>>> 96249d35711d4da51216c97d6753ca03cac18f41

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf: 
    include-in-header:
      - text: |
          \usepackage{cases}
          \usepackage{fvextra} 
          \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}



