project:
  type: book

book:
  title: "Algorithms & Data Structures Notes - SoSe 24"
  author: "Igor Dimitrov"
  date: "4/22/2024"
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
        - 02-intro/02-analysis.qmd
    - part: "Data Structures"
      chapters:
        - 03/01-lists.qmd
        - 03/02-arrays.qmd
        - 05/01-sorting.qmd

  downloads: pdf

number-depth: 2

bibliography: references.bib

highlight-style: pygments

format:
  html:
    theme: cosmo
  pdf: 
    code-block-border-left: true
    # code-block-bg: true
    include-in-header:
      - text: |
          \usepackage{cases}
          \usepackage{fvextra} 
          \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}



