test_bsearch: test_bsearch.cc bsearch_it.cc sort.hh qsort.cc search.hh
	g++ -o test_bsearch test_bsearch.cc bsearch_it.cc qsort.cc
test_lsearch: test_lsearch.cc
	g++ -o test_lsearch test_lsearch.cc
test_quick: quick_sort.cc
	g++ -o test_quick quick_sort.cc
test_merge: merge_sort.cc
	g++ -o test_merge merge_sort.cc
test_ins: ins_sort.cc
	g++ -o test_ins ins_sort.cc
test_sel: sel_sort.cc
	g++ -o test_sel sel_sort.cc

test_sort: test_sort.cc sort.hh selection_sort.cc insertion_sort.cc
	g++ -o test_sort test_sort.cc selection_sort.cc insertion_sort.cc

test_insert: insert_sort.cc
	g++ -o test_insert insert_sort.cc

test_qsort: qsort.cc
	g++ -o test_qsort qsort.cc