test_sort: test_sort.cc sort.hh selection_sort.cc insertion_sort.cc
	g++ -o test_sort test_sort.cc selection_sort.cc insertion_sort.cc
test_insert: insert_sort.cc
	g++ -o test_insert insert_sort.cc

test_qsort: qsort.cc
	g++ -o test_qsort qsort.cc